name: Download

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      
      - name: Download
        shell: bash
        env:
          HOST: ${{ secrets.HOST }}
          API_KEY: ${{ secrets.API_KEY }}
        run: ./download.sh

      - name: Commit
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BASE_BRANCH: master
          BRANCH: master
          FOLDER: .
          CLEAN: false
