name: Download

on:
  issue_comment:
    types: [created, edited, deleted]  
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      
      - name: Download
        shell: bash
        env:
          HOST: ${{ secrets.HOST }}
          API_KEY: ${{ secrets.API_KEY }}
        run: ./download.sh

      - name: Commit
        shell: bash
        run: |
          git config user.email "a@b.com"
          git config user.name "Test"          
          git commit -am -
          git push

      # - name: Commit
      #   uses: JamesIves/github-pages-deploy-action@releases/v3
      #   with:
      #     BASE_BRANCH: master
      #     BRANCH: master
      #     FOLDER: .
      #     CLEAN: false
